name: Deploy Production

on:
  push:
    branches:
      - "production_db_deploys_on_merge"

jobs:
  deploy-production:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get last commit SHA
        id: get_sha
        run: |
          echo sha="${{ github.event.before }}" | cut -c1-8 >> $GITHUB_OUTPUT

      - name: Run Prisma Migrate
        run: |
          touch .env
          echo '.env before'
          cat .env
          echo DATABASE_URL="${{ secrets.DATABASE_URL_LIVE_POOLED}}" >> .env
          echo DIRECT_DATABASE_URL="${{ secrets.DATABASE_URL_LIVE_DIRECT}}" >> .env
          echo '.env after'
          cat .env
          echo 'about to pmd'
          npx prisma migrate deploy
