name: Run Linting
run-name: ${{ github.actor }} is running linting on a PR
on: pull_request
jobs:
  Run-eslint-prettier:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
